server.port=8080

grpc.server.port=9090

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

lumina.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=lumina-exchange
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

resilience4j.circuitbreaker.instances.redis-ledger.sliding-window-size=10
resilience4j.circuitbreaker.instances.redis-ledger.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.redis-ledger.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.redis-ledger.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.redis-ledger.register-health-indicator=true
resilience4j.metrics.enabled=true
