apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumina-exchange.fullname" . }}-internal
  labels:
    {{- include "lumina-exchange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.internal.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.internal.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.internal.metricsPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "lumina-exchange.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumina-exchange.fullname" . }}-api
  labels:
    {{- include "lumina-exchange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "lumina-exchange.selectorLabels" . | nindent 4 }}
